[package]
name = "slint_demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "5.0.1"
image = "0.24.7"
noise = "0.8.2"
rand = "0.8.5"
slint = "1.1.1"
